<a href="https://colab.research.google.com/github/arijeetchoudhury100/Logic_Gates_Neural_Network/blob/master/logic_gate_simulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#simulate AND,OR,NOT,NAND,NOR using single layer perceptron 

In [1]:
import numpy as np

In [2]:
def initialize(n_x):
  W = np.zeros((1,n_x))
  b = 0
  return W,b

In [3]:
def hardlim(n):
  if n<0:
    return 0
  else:
    return 1

In [11]:
X_and = np.array([[0,0],[0,1],[1,0],[1,1]]).T
y_and = np.array([0,0,0,1]).reshape(1,4)

X_or = X_and
y_or = np.array([0,1,1,1]).reshape(1,4)

X_nand = X_and
y_nand = np.array([1,1,1,0]).reshape(1,4)

X_nor = X_and
y_nor = np.array([1,0,0,0]).reshape(1,4)

X_not = np.array([0,1]).reshape(1,2)
y_not = np.array([1,0]).reshape(1,2)

X_test = X_and
y_test = np.array([0,0,1,0]).reshape(1,4)

In [20]:
def model(X,y):
  W , b = initialize(X.shape[0])
  itr = 0
  while True:
    W_old = W
    b_old = b
    itr += 1
    for i in range(X.shape[1]):
      a = hardlim(np.dot(W,X[:,i].reshape(X.shape[0],1)) + b)
      e = y[0][i] - a
      W = W + e*X[:,i].reshape(1,X.shape[0])
      b = b + e
      print(W)
      print(b)
    if np.array_equal(W_old,W) and b_old == b:
      break
  return itr,W,b

In [16]:
_,W_and,b_and = model(X_and,y_and)
print('Weight: ',W_and)
print('Bias: ',b_and)

Weight:  [[2. 1.]]
Bias:  -3


In [7]:
_,W_or,b_or = model(X_or,y_or)
print('Weight: ',W_or)
print('Bias: ',b_or)

Weight:  [[1. 1.]]
Bias:  -1


In [8]:
_,W_nor,b_nor = model(X_nor,y_nor)
print('Weight: ',W_nor)
print('Bias: ',b_nor)

Weight:  [[-1. -1.]]
Bias:  0


In [9]:
_,W_nand,b_nand = model(X_nand,y_nand)
print('Weight: ',W_nand)
print('Bias: ',b_nand)

Weight:  [[-2. -1.]]
Bias:  2


In [10]:
_,W_not,b_not = model(X_not,y_not)
print('Weight: ',W_not)
print('Bias: ',b_not)

Weight:  [[-1.]]
Bias:  0


In [21]:
itr,W_test,b_test = model(X_test,y_test)
print('Weight: ',W_test)
print('Bias: ',b_test)
print(itr)

[[0. 0.]]
-1
[[0. 0.]]
-1
[[1. 0.]]
0
[[ 0. -1.]]
-1
[[ 0. -1.]]
-1
[[ 0. -1.]]
-1
[[ 1. -1.]]
0
[[ 0. -2.]]
-1
[[ 0. -2.]]
-1
[[ 0. -2.]]
-1
[[ 1. -2.]]
0
[[ 1. -2.]]
0
[[ 1. -2.]]
-1
[[ 1. -2.]]
-1
[[ 1. -2.]]
-1
[[ 1. -2.]]
-1
[[ 1. -2.]]
-1
[[ 1. -2.]]
-1
[[ 1. -2.]]
-1
[[ 1. -2.]]
-1
Weight:  [[ 1. -2.]]
Bias:  -1
5
